CREATE TABLE items (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    weight DECIMAL(10,2) DEFAULT 0.0,
    price DECIMAL(10,2) DEFAULT 0.0,
    item_type ENUM ('WEAPON', 'ARMOUR', 'CYPHER', 'ARTIFACT', 'EQUIPMENT', 'ODDITY', 'AMMUNITION') NOT NULL,
    equip_location ENUM ('HEAD', 'EYES', 'EARS', 'NECK', 'TORSO', 'LEGS', 'HANDS', 'FOREARM', 'FEET', 'NONE') DEFAULT 'NONE'
)