CREATE TABLE skills (
    id VARCHAR(36) PRIMARY KEY DEFAULT(UUID()),
    name VARCHAR(100) NOT NULL,
    category ENUM('MIGHT', 'SPEED', 'INTELLECT', 'CUSTOM', 'SPECIAL_ABILITY') NOT NULL,
    description TEXT,
    attack_modifier SMALLINT DEFAULT 0,
    armour_modifier SMALLINT DEFAULT 0,

    cost VARCHAR(100),
    type ENUM('ACTION', 'PASSIVE', 'ENABLER', 'DEFENCE', 'UTILITY', 'SKILL_SLOT', 'FIGHTING_MOVE_CHOICE_SLOT', 'FIGHTING_MOVE', 'ESOTERY_CHOICE_SLOT', 'ESOTERY', 'TRICK_OF_THE_TRADE_SLOT', 'TRICK_OF_THE_TRADE') DEFAULT 'PASSIVE'
);