CREATE TABLE IF NOT EXISTS special_abilities (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    type VARCHAR(100) NOT NULL,
    tier INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);