CREATE TABLE IF NOT EXISTS characters (
    id VARCHAR(36) PRIMARY KEY DEFAULT(UUID()),
    name VARCHAR(100) NOT NULL,
    descriptor_id VARCHAR(36),
    type VARCHAR(50),
    focus VARCHAR(50),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (descriptor_id) REFERENCES character_descriptors (id) ON DELETE SET NULL
)