CREATE TABLE IF NOT EXISTS skill_proficiencies (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    level VARCHAR(100) NOT NULL,
    modifier INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);